### ISSUE TITLE
Refreshing

### ISSUE THREAD

**Issue by drtiwarir** [YoCodeCrafters/tataplay-generator#1]
Do you have to login every day to generate a new m3u link ?
Nat Geo Wild HD is not working ?
Great work, I am running on a webhost
Thanks

**Comment by SabBits** [comment]
**1.** No, you don't have to run it every day; the playlist should be valid for a month. 
**2.** If any channel isn't working, then it's an issue from TATAPLAY, and there's not much we can do about it. 

You're most welcome :)

**Comment by drtiwarir** [comment]
Thanks bro
Really appreciate your work
